AWSTemplateFormatVersion: '2010-09-09'
Description: 'Curso AWS ElastiCache - Ambiente automatizado para alunos'

Parameters:
  PrefixoAluno:
    Type: String
    Default: aluno
    Description: Prefixo para nomes dos alunos
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC onde os recursos serao criados
  
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet publica para instancias EC2
  
  AllowedCIDR:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR permitido para acesso SSH
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Nome da chave SSH para acesso as instancias
  
  ConsolePasswordSecret:
    Type: String
    Description: Nome do secret no Secrets Manager contendo a senha do console

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c02fb55956c7d316
    us-east-2:
      AMI: ami-0807bd3aff0ae7273
    us-west-1:
      AMI: ami-0d9858aa3c6322f73
    us-west-2:
      AMI: ami-008fe2fc65df48dac
    eu-west-1:
      AMI: ami-01dd271720c1ba44f
    eu-central-1:
      AMI: ami-0f454ec961da9a046
    sa-east-1:
      AMI: ami-0c820c196a818d66a

Resources:
  # IAM Group para alunos
  CursoElastiCacheStudentsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: curso-elasticache-students
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsReadOnlyAccess
      Policies:
        - PolicyName: ElastiCacheLabPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeVpcs
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeNetworkInterfaces
                  - ec2:CreateSecurityGroup
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:AuthorizeSecurityGroupEgress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupEgress
                  - ec2:DeleteSecurityGroup
                  - ec2:CreateTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::curso-elasticache-labs-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::curso-elasticache-labs-${AWS::AccountId}/*'
              - Effect: Allow
                Action:
                  - sts:GetCallerIdentity
                Resource: '*'

  # Security Group para instancias EC2 dos alunos
  AlunosSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: curso-elasticache-alunos-sg
      GroupDescription: Security group para instancias EC2 dos alunos
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
          Description: SSH access
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: All outbound traffic
      Tags:
        - Key: Name
          Value: curso-elasticache-alunos-sg
        - Key: Curso
          Value: ElastiCache

  # Security Group para clusters ElastiCache
  ElastiCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: curso-elasticache-clusters-sg
      GroupDescription: Security group para clusters ElastiCache
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref AlunosSecurityGroup
          Description: Redis access from student instances
      Tags:
        - Key: Name
          Value: curso-elasticache-clusters-sg
        - Key: Curso
          Value: ElastiCache

  # Bucket S3 para laboratorios
  LabsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'curso-elasticache-labs-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Curso
          Value: ElastiCache

  # Usuario IAM para aluno01
  Ualuno01User:
    Type: AWS::IAM::User
    Properties:
      UserName: curso-elasticache-aluno01
      Groups:
        - !Ref CursoElastiCacheStudentsGroup
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${ConsolePasswordSecret}:SecretString:password}}'
        PasswordResetRequired: false
      Tags:
        - Key: Aluno
          Value: aluno01
        - Key: Curso
          Value: ElastiCache

  # Access Keys para aluno01
  Ualuno01AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref Ualuno01User

  # Instancia EC2 para aluno01
  Ualuno01Instance:
    Type: AWS::EC2::Instance
    DependsOn: 
      - LabsBucket
      - Ualuno01InstanceProfile
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref AlunosSecurityGroup
      IamInstanceProfile: !Ref Ualuno01InstanceProfile
      UserData:
        Fn::Base64: !Sub 
          - |
            #!/bin/bash
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            echo "=== INICIANDO SETUP PARA aluno01 EM $(date) ==="
            
            # Aguardar conectividade com internet
            echo "Testando conectividade com internet..."
            for i in {1..30}; do
              if curl -s --connect-timeout 5 https://github.com >/dev/null; then
                echo "✅ Internet acessível!"
                break
              fi
              echo "⏳ Tentativa $i/30: Aguardando conectividade..."
              sleep 10
            done
            
            # Baixar script de setup diretamente do GitHub
            echo "📥 Baixando script de setup do GitHub..."
            GITHUB_SCRIPT_URL="https://raw.githubusercontent.com/DevWizardsOps/Curso-elasticache/main/preparacao-curso/setup-aluno.sh"
            
            if curl -fsSL "$GITHUB_SCRIPT_URL" -o /tmp/setup-aluno.sh; then
              echo "✅ Script baixado com sucesso do GitHub"
              chmod +x /tmp/setup-aluno.sh
              
              echo "🚀 Executando setup para aluno01..."
              /tmp/setup-aluno.sh "aluno01" "${AWS::Region}" "${AccessKey}" "${SecretKey}" >> /var/log/setup-aluno.log 2>&1
              SETUP_EXIT_CODE=$?
              echo "✅ Setup concluído com código: $SETUP_EXIT_CODE"
              
              # Verificar se o usuário foi criado
              if id "aluno01" &>/dev/null; then
                echo "✅ Usuário aluno01 criado com sucesso"
              else
                echo "❌ Falha ao criar usuário aluno01"
                SETUP_EXIT_CODE=1
              fi
            else
              echo "❌ Falha ao baixar script do GitHub"
              SETUP_EXIT_CODE=1
            fi
            
            # Se falhou, executar configuração básica de fallback
            if [ $SETUP_EXIT_CODE -ne 0 ]; then
              echo "🔄 Executando configuração básica de fallback..."
              yum update -y
              yum install -y git htop tree wget unzip jq bc redis6 redis6-doc --skip-broken
              curl -fsSL https://rpm.nodesource.com/setup_18.x | bash - || true
              yum install -y nodejs python3 python3-pip --skip-broken
              
              # Criar estrutura básica
              mkdir -p /home/ec2-user/labs
              echo "Ambiente básico configurado em $(date)" > /home/ec2-user/labs/setup-status.txt
              echo "ERRO: Setup completo falhou, usando configuração básica" >> /home/ec2-user/labs/setup-status.txt
              chown -R ec2-user:ec2-user /home/ec2-user/labs
              
              # Tentar criar usuário básico
              if ! id "aluno01" &>/dev/null; then
                useradd -m -s /bin/bash aluno01 || true
                echo "aluno01 ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers || true
                
                # Copiar chave SSH
                if [ -d "/home/ec2-user/.ssh" ]; then
                  mkdir -p /home/aluno01/.ssh
                  cp /home/ec2-user/.ssh/authorized_keys /home/aluno01/.ssh/authorized_keys || true
                  chown -R aluno01:aluno01 /home/aluno01/.ssh || true
                  chmod 700 /home/aluno01/.ssh || true
                  chmod 600 /home/aluno01/.ssh/authorized_keys || true
                fi
                
                # Configurar variável ID básica
                echo "export ID=aluno01" >> /home/aluno01/.bashrc || true
                chown aluno01:aluno01 /home/aluno01/.bashrc || true
              fi
              
              SETUP_EXIT_CODE=0  # Não falhar o CloudFormation por causa do fallback
            fi
            
            echo "=== FINALIZANDO USER-DATA EM $(date) ==="
            echo "Código de saída final: $SETUP_EXIT_CODE"
            
            # Sinalizar conclusão para CloudFormation
            /opt/aws/bin/cfn-signal -e $SETUP_EXIT_CODE --stack ${AWS::StackName} --resource Ualuno01Instance --region ${AWS::Region}
          - AccessKey: !Ref Ualuno01AccessKey
            SecretKey: !GetAtt Ualuno01AccessKey.SecretAccessKey
      Tags:
        - Key: Name
          Value: curso-elasticache-aluno01
        - Key: Aluno
          Value: aluno01
        - Key: Curso
          Value: ElastiCache
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT15M

  # IAM Role para instancia EC2 do aluno01
  Ualuno01InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: curso-elasticache-aluno01-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: ElastiCacheLabInstancePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::curso-elasticache-labs-${AWS::AccountId}'
                  - !Sub 'arn:aws:s3:::curso-elasticache-labs-${AWS::AccountId}/*'
      Tags:
        - Key: Aluno
          Value: aluno01
        - Key: Curso
          Value: ElastiCache

  # Instance Profile para aluno01
  Ualuno01InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: curso-elasticache-aluno01-profile
      Roles:
        - !Ref Ualuno01InstanceRole


Outputs:
  StackName:
    Description: Nome da stack CloudFormation
    Value: !Ref AWS::StackName
    Export:
      Name: !Sub '${AWS::StackName}-StackName'

  VPCId:
    Description: VPC ID utilizada
    Value: !Ref VpcId
    Export:
      Name: !Sub '${AWS::StackName}-VPC-ID'

  AlunosSecurityGroupId:
    Description: Security Group ID para alunos
    Value: !Ref AlunosSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-Alunos-SG-ID'

  ElastiCacheSecurityGroupId:
    Description: Security Group ID para ElastiCache
    Value: !Ref ElastiCacheSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ElastiCache-SG-ID'

  LabsBucketName:
    Description: Nome do bucket S3 para laboratorios
    Value: !Ref LabsBucket
    Export:
      Name: !Sub '${AWS::StackName}-Labs-Bucket'

  ConsolePasswordSecret:
    Description: Nome do secret contendo a senha do console
    Value: !Ref ConsolePasswordSecret
    Export:
      Name: !Sub '${AWS::StackName}-ConsolePassword-Secret'

  SecretsManagerURL:
    Description: Link para o Secrets Manager
    Value: !Sub 'https://console.aws.amazon.com/secretsmanager/home?region=${AWS::Region}#!/secret?name=${ConsolePasswordSecret}'

  Ualuno01PublicIP:
    Description: IP publico da instancia do aluno01
    Value: !GetAtt Ualuno01Instance.PublicIp
    Export:
      Name: !Sub '${AWS::StackName}-Ualuno01-Public-IP'

  Ualuno01PrivateIP:
    Description: IP privado da instancia do aluno01
    Value: !GetAtt Ualuno01Instance.PrivateIp
    Export:
      Name: !Sub '${AWS::StackName}-Ualuno01-Private-IP'

  Ualuno01InstanceId:
    Description: Instance ID do aluno01
    Value: !Ref Ualuno01Instance
    Export:
      Name: !Sub '${AWS::StackName}-Ualuno01-Instance-ID'

  Ualuno01AccessKeyId:
    Description: Access Key ID do aluno01
    Value: !Ref Ualuno01AccessKey
    Export:
      Name: !Sub '${AWS::StackName}-Ualuno01-Access-Key-ID'

  Ualuno01SecretAccessKey:
    Description: Secret Access Key do aluno01
    Value: !GetAtt Ualuno01AccessKey.SecretAccessKey
    Export:
      Name: !Sub '${AWS::StackName}-Ualuno01-Secret-Access-Key'

